apiVersion: v1
kind: Service
metadata:
  name: html-customer-app-service
  namespace: app
spec:
  selector:
    app: html-customer-app
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80 
  type: LoadBalancer 