apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-customer-app
  namespace: app
  labels:
    app: html-customer-app
    desafio: jackexperts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-customer-app
  template:
    metadata:
      labels:
        app: html-customer-app
        desafio: jackexperts
    spec:
      containers:
      - name: html-container
        image: jottakayoml/html-custom-app:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: customer.html
      volumes:
      - name: html-volume
        configMap:
          name: html-customer-config
      securityContext:
        runAsUser: 1000