apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-customer-app
  namespace: app
  labels:
    app: html-customer-app
    desafio: jackexperts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-customer-app
  template:
    metadata:
      labels:
        app: html-customer-app
        desafio: jackexperts
    spec:
      containers:
      - name: html-container
        image: jottakayoml/html-custom-app:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/customer.html
          subPath: customer.html
      volumes:
      - name: html-volume
        configMap:
          name: html-customer-config
---
apiVersion: v1
kind: Service
metadata:
  name: html-customer-app-service
  namespace: app
spec:
  selector:
    app: html-customer-app
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80 
  type: LoadBalancer 