name: Build and Push Docker Image

on:
  push:
    branches:
      - pipeline-feature
  pull_request:
    branches:
      - pipeline-feature

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

    - name: Build the Docker image
      run: |
        cd app
        docker build -t jottakayoml/html-custom-app:latest .

    - name: Push the Docker image
      run: |
        docker push jottakayoml/html-custom-app:latest