name: Build and Push Docker Image

on:
  push:
    branches:
      - pipeline-feature
  pull_request:
    branches:
      - pipeline-feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push the Docker image
      run: |
        cd app
        docker build -t jottakayoml/html-custom-app:latest .
        docker push jottakayoml/html-custom-app:latest

    - name: Deploy to Kubernetes
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        pwd
        cd app
        echo "${KUBE_CONFIG_DATA}" | base64 --decode > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        helm install html-customer-app .
