name: Build and Push Docker Image

on:
  push:
    branches:
      - pipeline-feature
  pull_request:
    branches:
      - pipeline-feature
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: jottakayoml #${{ secrets.DOCKER_USERNAME }}
        password: dckr_pat_tUnnpMVMCBV2TMHZeipHNJn1ZZ8 #${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        cd app
        docker build -t jottakayoml/html-custom-app:latest .

    - name: Push the Docker image
      run: |
        docker push jottakayoml/html-custom-app:latest